spring:
  application: 
    name: booking_api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/moviebooking
    username: alex
    password: alex
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8763
  
eureka:
  instance:
    hostname: booking_api
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/

movieadmin-config:
  movieAdminUrl: http://admin_api
