services:
  eureka_server:
    image: "spring-cloud-netflix-example/eureka-server"
    hostname: eureka_server
    ports:
      - "8761:8761"
    networks:
      - default
  admin_service:
    container_name: "admin_api"
    build:
      context: /root/movies-app
      dockerfile: movie-admin/Docker/Dockerfile
    restart: always
    ports:
      - 8762:8762
    depends_on:
      - eureka_server
      - mysql_db
    networks:
      - default
  booking_service:
    container_name: "booking_api"
    build:
      context: /root/movies-app
      dockerfile: movie-booking/Docker/Dockerfile
    restart: always
    ports:
      - 8763:8763
    depends_on:
      - eureka_server
      - mysql_db
    networks:
      - default
  mysql_db:
    container_name: "mysql_db"
    image: "mysql:8.3"
    restart: always
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      MYSQL_DATABASE: moviebooking
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: admin
networks:
  default:
    driver: bridge
