version: "4"
services:
  eureka_service:
    build:
      context: /root/movies-app
      dockerfile: eureka-movies-server/Docker/Dockerfile
    restart: always
    ports:
      - 8761:8761
  admin_service:
    build:
      context: /root/movies-app
      dockerfile: movie-admin/Docker/Dockerfile
    restart: always
    ports:
      - 8762:8762
    depends_on:
      - eureka_service
      - mysql_db
  booking_service:
    build:
      context: /root/movies-app
      dockerfile: movie-booking/Docker/Dockerfile
    restart: always
    ports:
      - 8763:8763
    depends_on:
      - eureka_service
      - mysql_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: moviebooking
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: admin
