spring:
  application:
    name: eureka_server
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-sistem-access: false

server:
  port: 8761
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
