spring:
  application: 
    name: admin_api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/moviebooking
    username: alex
    password: alex
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8762
  
eureka:
  instance:
    hostname: admin_api
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

